### ISSUE TITLE
RFW00010: Prompt writing app

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/creative-prompt-writing#1]
**Description**:
We have lots of Tibetan creative write up collected from various sources. We would like our annotators to write prompt for those creative write up so that we can use those creative write up and prompt together to fine tune our Tibetan LLM to write those crative write up. Therefore we need a simple editor on pecha tools where we can load the creative write up and text area where our annotators can read the write up and write suitable prompt for generating those write up in that text area and submit it.
We need a skip option if we have loaded unexpected creative write up.
We need a separate UI for our reviewer who can reject if the prompt is not suitable for the creative write up.

**Illustration**:

_Annotator UI_
![Image](https://github.com/user-attachments/assets/68e46cae-7026-478f-b59b-bd1785be9909)

_Reviewer UI_
![Image](https://github.com/user-attachments/assets/c757db40-ed65-4b96-9bda-de4d928ba78a)

**Note**
We would like to have the other features such as:
- Salary Report generation as per annotator and reviewer

**Sub-tasks**
- [x] Set up a remix project
- [x] prisma schema setup + db connect
- [x] UI of prompt writing
- [x] api calls for annotator
- [x] api calls for reviewer
- [x] api calls for admin + add text + user dashboard
- [x] API calls for report with user stats
- [x] add lazy loaded history for annotator
- [x] add lazy loaded history for reviewer
- [x] deploy app for pecha tool and integrate it in [www.pecha.tools](http://www.pecha.tools/)
